spring:
  profiles:
    active: dev

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yml
  jackson:
    serialization.write_dates_as_timestamps: false

jwt:
  secret: ${JWS_SECRET}
  expirationMs: 1200000
  refreshExpirationMs: 3200000

user:
  password:
    default: ${POSTGRE_PASS}

