version: "3.1"

services:
  db:
    image: postgres:12.8-alpine3.14
    restart: always
    ports:
     - 9999:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crm