
CREATE SEQUENCE usr_seq START WITH 1;

CREATE TABLE usr (
    id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('usr_seq'),
    email VARCHAR(128) NOT NULL UNIQUE,
    password varchar(128) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);